"""
Advisory engine: turns (dilemma text, country, sector, lang) into a
structured advisory report.

This is the "retrieval augmented" half of the prototype described in the
thesis. Rather than asking a large language model to answer freely, the
pipeline is:

    1. classify   -> TensorFlow model scores the dilemma against five
                      ethical dimensions (engine input)
    2. retrieve   -> pick knowledge-base entries whose category, country
                      and sector match the dilemma
    3. compose    -> assemble a structured, sourced report with an
                      explicit disclaimer, in the requested language

Keeping retrieval and composition rule-based (rather than delegating to a
generative model) keeps every sentence in the response traceable to a
source in data/knowledge_base.json, which is exactly the "explainable,
auditable, context-sensitive guidance" goal stated in the proposal.

Bilingual support (en/el): the knowledge base stores each label,
description, and entry text as {"en": ..., "el": ...}. This module picks
the right one based on the `lang` argument, defaulting to "en" for any
missing translation so a partially-translated addition never breaks.
"""

# -----------------------------------------------------------------------
# Εισαγωγές βιβλιοθηκών και εσωτερικών ενοτήτων
# -----------------------------------------------------------------------
import json
import os
import re

from engine.llm_client import LLMUnavailable, classify_dilemma

# -----------------------------------------------------------------------
# Σταθερές ρυθμίσεων: διαδρομή βάσης γνώσης, όρια ανίχνευσης, γλώσσες
# -----------------------------------------------------------------------
KB_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "knowledge_base.json")

DETECTION_THRESHOLD = 0.45  # εφεδρικό κατώφλι, για κατηγορίες που δεν αναφέρονται παρακάτω
# Κατώφλι ανίχνευσης ανά ηθική διάσταση. Ξεκινούν όλα στην ίδια τιμή
# (0.45) απλώς ως ένα λογικό σημείο εκκίνησης· ενημέρωσέ τα με τις
# τιμές που προτείνει το `python -m model.evaluate_classifier` (ενότητα
# «Βέλτιστο κατώφλι ανά κατηγορία»), αφού κάθε ηθική διάσταση έχει
# διαφορετική "δυσκολία" ανίχνευσης και ένα ενιαίο κατώφλι για όλες δεν
# είναι βέλτιστο.
DETECTION_THRESHOLDS = {
    "transparency": 0.30,
    "fairness": 0.40,
    "non_maleficence": 0.25,
    "accountability": 0.50,
    "privacy": 0.40,
}
MIN_DETECTED_DIMENSIONS = 1
GENERAL = "General / Other"
SUPPORTED_LANGS = ("en", "el")
DEFAULT_LANG = "en"

# Τα 27 κράτη-μέλη της ΕΕ· χρησιμοποιούνται ώστε μια εγγραφή με ετικέτα
# χώρας "European Union" (π.χ. ΓΚΠΔ, EU AI Act — άμεσα εφαρμοστέοι
# κανονισμοί) να εμφανίζεται αυτόματα σε όποιον επιλέξει οποιοδήποτε
# συγκεκριμένο κράτος-μέλος, όχι μόνο σε όποιον επιλέξει κυριολεκτικά
# "European Union".
EU_MEMBER_STATES = {
    "Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czech Republic",
    "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary",
    "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta",
    "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia",
    "Spain", "Sweden",
}

# Οι 50 πολιτείες των ΗΠΑ συν η Ουάσινγκτον D.C.· ίδια λογική με τα
# κράτη-μέλη της ΕΕ, αλλά για γνησίως ομοσπονδιακούς νόμους (π.χ. Title
# VII, ECOA) με ετικέτα χώρας "United States".
US_STATES = {
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine",
    "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi",
    "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia",
    "Washington", "West Virginia", "Wisconsin", "Wyoming",
    "District of Columbia",
}

# Κατώφλι χαμηλής εμπιστοσύνης: αν ο ταξινομητής TensorFlow δεν είναι
# βέβαιος για καμία κατηγορία, ενεργοποιείται (εφόσον έχει ρυθμιστεί) η
# ενισχυτική ταξινόμηση μέσω LLM στη συνάρτηση _maybe_enhance_with_llm.
LOW_CONFIDENCE_MAX = 0.3

# -----------------------------------------------------------------------
# Κείμενο αποποίησης ευθύνης, διαθέσιμο στις δύο υποστηριζόμενες γλώσσες
# -----------------------------------------------------------------------
DISCLAIMER = {
    "en": (
        "This report is generated by a prototype research tool and is general guidance only. "
        "It is not legal advice, does not replace review by a qualified lawyer or compliance officer, "
        "and may not reflect the most recent regulatory changes."
    ),
    "el": (
        "Η αναφορά προέρχεται από ερευνητικό πρωτότυπο και δίνει μόνο γενική καθοδήγηση. "
        "Δεν αποτελεί νομική συμβουλή, δεν αντικαθιστά τον έλεγχο από δικηγόρο ή υπεύθυνο κανονιστικής "
        "συμμόρφωσης και ίσως δεν περιλαμβάνει τις πιο πρόσφατες αλλαγές της νομοθεσίας."
    ),
}


# -----------------------------------------------------------------------
# Κανονικοποίηση κωδικού γλώσσας σε μία από τις υποστηριζόμενες τιμές
# -----------------------------------------------------------------------
def _lang(lang: str) -> str:
    return lang if lang in SUPPORTED_LANGS else DEFAULT_LANG


# Κανονικές εκφράσεις για την ανίχνευση ελληνικού αλφαβήτου στο κείμενο
_GREEK_CHARS_RE = re.compile(r"[\u0370-\u03FF\u1F00-\u1FFF]")
_LETTERS_RE = re.compile(r"[^\W\d_]", re.UNICODE)


# -----------------------------------------------------------------------
# Αυτόματη ανίχνευση γλώσσας βάσει του αλφαβήτου του διλήμματος
# -----------------------------------------------------------------------
def detect_lang(text: str, fallback: str = DEFAULT_LANG) -> str:
    """Best-effort language detection from the dilemma's own script.

    This is symmetric: a Greek-script dilemma forces "el", and an
    English/Latin-script dilemma forces "en" — regardless of whatever the
    UI toggle last sent. Earlier this only pushed toward Greek and let
    English silently inherit the previous request's language, so once a
    Greek dilemma was submitted the report would incorrectly "stick" to
    Greek for every English dilemma after it. `fallback` is now only used
    when the text carries no letters at all (e.g. empty, or numbers only).
    """
    if not text:
        return _lang(fallback)
    letters = _LETTERS_RE.findall(text)
    if not letters:
        return _lang(fallback)
    greek_chars = _GREEK_CHARS_RE.findall(text)
    if len(greek_chars) / len(letters) > 0.3:
        return "el"
    return "en"


# -----------------------------------------------------------------------
# Επιλογή της σωστής μεταφρασμένης τιμής από ένα δίγλωσσο λεξικό
# -----------------------------------------------------------------------
def _pick(value, lang: str):
    """Pick the localized string from a {"en":..., "el":...} dict, or return
    the value unchanged if it's already a plain string (back-compat)."""
    if isinstance(value, dict):
        return value.get(lang) or value.get(DEFAULT_LANG) or ""
    return value


# -----------------------------------------------------------------------
# Φόρτωση της βάσης γνώσης από το αρχείο JSON
# -----------------------------------------------------------------------
def load_knowledge_base(path: str = KB_PATH) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# -----------------------------------------------------------------------
# Απόφαση αν θα ενεργοποιηθεί η ενισχυτική ταξινόμηση μέσω LLM: ενεργή
# αυτόματα για το Ollama (τοπικό, χωρίς κόστος), απαιτεί ρητή ενεργοποίηση
# για εξωτερικούς παρόχους (OpenAI/Anthropic) ώστε να αποφεύγεται
# απρόβλεπτο κόστος ανά κλήση
# -----------------------------------------------------------------------
def _llm_fallback_enabled() -> bool:
    override = os.environ.get("LLM_CLASSIFICATION_FALLBACK", "").strip().lower()
    if override in ("true", "1", "yes"):
        return True
    if override in ("false", "0", "no"):
        return False
    return os.environ.get("LLM_PROVIDER", "").strip().lower() == "ollama"


# -----------------------------------------------------------------------
# Ενίσχυση των βαθμολογιών ταξινόμησης μέσω LLM, μόνο όταν ο τοπικός
# ταξινομητής δεν είναι σίγουρος για καμία κατηγορία
# -----------------------------------------------------------------------
def _maybe_enhance_with_llm(dilemma: str, scores: dict) -> tuple:
    """Blend in an LLM classification pass when the local model is unsure
    about everything. Returns (scores, llm_assisted: bool)."""
    if max(scores.values(), default=0.0) >= LOW_CONFIDENCE_MAX:
        return scores, False
    if not _llm_fallback_enabled():
        return scores, False

    try:
        llm_scores = classify_dilemma(dilemma)
    except LLMUnavailable as exc:
        print(f"[advisor] LLM classification fallback skipped: {exc}")
        return scores, False

    blended = {cat: max(scores.get(cat, 0.0), llm_scores.get(cat, 0.0)) for cat in scores}
    return blended, True


# -----------------------------------------------------------------------
# Επιλογή των ηθικών διαστάσεων που ξεπερνούν το κατώφλι ανίχνευσης
# -----------------------------------------------------------------------
def _select_detected_dimensions(scores: dict) -> list:
    """Pick categories above their (per-category) detection threshold; if none
    qualify, fall back to the single highest-scoring category."""
    above = [
        cat for cat, score in scores.items()
        if score >= DETECTION_THRESHOLDS.get(cat, DETECTION_THRESHOLD)
    ]
    if len(above) >= MIN_DETECTED_DIMENSIONS:
        return sorted(above, key=lambda c: -scores[c])
    top_category = max(scores, key=scores.get)
    return [top_category] if scores[top_category] > 0 else []


# -----------------------------------------------------------------------
# Έλεγχος αν μια εγγραφή της βάσης γνώσης ταιριάζει με τη χώρα/κλάδο
# -----------------------------------------------------------------------
def _matches(entry: dict, country: str, sector: str) -> bool:
    entry_country = entry.get("country", GENERAL)
    entry_sector = entry.get("sector", GENERAL)
    country_ok = (
        entry_country in (country, GENERAL)
        # Κανονισμοί με ετικέτα "European Union" (π.χ. ΓΚΠΔ, EU AI Act)
        # ισχύουν άμεσα σε κάθε κράτος-μέλος, οπότε εμφανίζονται και σε
        # όποιον επιλέξει συγκεκριμένο κράτος-μέλος, όχι μόνο "European Union"
        or (entry_country == "European Union" and country in EU_MEMBER_STATES)
        # Αντίστοιχα, κανόνες με ετικέτα "United States" που είναι γνησίως
        # ομοσπονδιακοί (π.χ. Title VII, ECOA) ισχύουν σε κάθε πολιτεία
        or (entry_country == "United States" and country in US_STATES)
    )
    sector_ok = entry_sector in (sector, GENERAL)
    return country_ok and sector_ok


# -----------------------------------------------------------------------
# Ανάκτηση εγγραφών συγκεκριμένου τύπου (αρχή / κανονισμός / ενέργεια)
# που ταιριάζουν με τις εντοπισμένες κατηγορίες, τη χώρα και τον κλάδο
# -----------------------------------------------------------------------
def _entries_by_type(kb: dict, categories: list, country: str, sector: str, entry_type: str, lang: str) -> list:
    results = []
    for entry in kb["entries"]:
        if entry["type"] != entry_type:
            continue
        # Μια εγγραφή μπορεί να αφορά περισσότερες διαστάσεις (πεδίο
        # "categories"), π.χ. το δικαίωμα εξήγησης σε αυτοματοποιημένη
        # πιστοληπτική αξιολόγηση αφορά και τη διαφάνεια και τη λογοδοσία.
        # Εμφανίζεται αν έχει εντοπιστεί οποιαδήποτε από αυτές, με ετικέτα
        # την πρώτη (κατά σειρά βαθμολογίας) που εντοπίστηκε.
        entry_categories = entry.get("categories") or [entry["category"]]
        matched = next((c for c in categories if c in entry_categories), None)
        # Οι εγγραφές του συγκεκριμένου κλάδου που επέλεξε ο χρήστης
        # εμφανίζονται πάντα, ακόμη κι αν ο ταξινομητής δεν εντόπισε τη
        # διάστασή τους: αποτελούν το βασικό πλαίσιο κανόνων του κλάδου, και
        # έτσι μια οριακή βαθμολογία του ταξινομητή δεν κρύβει π.χ. τους
        # κανόνες για τα δεδομένα πελατών μιας δικηγορικής εταιρείας.
        sector_specific = sector != GENERAL and entry.get("sector", GENERAL) == sector
        if matched is None and not sector_specific:
            continue
        if not _matches(entry, country, sector):
            continue
        item = {
            "id": entry["id"],
            "category": matched or entry_categories[0],
            "text": _pick(entry["text"], lang),
            "source": entry["source"],
        }
        # Τα πεδία νομικής παραπομπής υπάρχουν μόνο σε εγγραφές τύπου "κανονισμός".
        if "article" in entry:
            item["article"] = _pick(entry["article"], lang)
        if "url" in entry:
            item["url"] = entry["url"]
        if "citation" in entry:
            item["citation"] = entry["citation"]
        results.append(item)
    return results


# -----------------------------------------------------------------------
# Κύρια συνάρτηση: εκτελεί ολόκληρη την αλυσίδα ταξινόμηση -> ανάκτηση
# -> σύνθεση για ένα δίλημμα και επιστρέφει τη δομημένη αναφορά
# -----------------------------------------------------------------------
def analyze(dilemma: str, country: str, sector: str, classifier, kb: dict = None, lang: str = DEFAULT_LANG,
            extra_dimensions: list = None) -> dict:
    """Run the full classify -> retrieve -> compose pipeline for one dilemma.

    `extra_dimensions`: dimensions implied by the AI Act risk tier (see
    engine/risk_tier.py). They are added to retrieval when the classifier
    missed them, without changing the classifier's scores.
    """
    kb = kb or load_knowledge_base()
    lang = _lang(lang)
    country = country if country in kb["countries"] else GENERAL
    sector = sector if sector in kb["sectors"] else GENERAL

    # Βήμα 1: ταξινόμηση του διλήμματος στις πέντε ηθικές διαστάσεις,
    # με προαιρετική ενίσχυση μέσω LLM όταν η εμπιστοσύνη είναι χαμηλή
    scores = classifier.predict(dilemma)
    scores, llm_assisted = _maybe_enhance_with_llm(dilemma, scores)
    detected = _select_detected_dimensions(scores)
    # Διαστάσεις που προκύπτουν από τη βαθμίδα κινδύνου και δεν εντοπίστηκαν
    added = [d for d in (extra_dimensions or []) if d in scores and d not in detected]
    detected = detected + added

    # Βήμα 2: ανάκτηση σχετικών αρχών, κανονισμών και ενεργειών από τη
    # βάση γνώσης, φιλτραρισμένων ανά εντοπισμένη κατηγορία, χώρα, κλάδο
    principles = _entries_by_type(kb, detected, country, sector, "principle", lang)
    regulations = _entries_by_type(kb, detected, country, sector, "regulation", lang)
    actions = _entries_by_type(kb, detected, country, sector, "action", lang)

    # Αφαίρεση τυχόν διπλότυπων εγγραφών, διατηρώντας τη σειρά εμφάνισης
    def dedupe(entries):
        seen = set()
        out = []
        for e in entries:
            if e["id"] not in seen:
                seen.add(e["id"])
                out.append(e)
        return out

    principles, regulations, actions = dedupe(principles), dedupe(regulations), dedupe(actions)

    # Βήμα 3: σύνθεση της τελικής, δομημένης απάντησης προς το frontend
    dimensions_out = [
        {
            "key": cat,
            "label": _pick(kb["categories"][cat]["label"], lang),
            "description": _pick(kb["categories"][cat]["description"], lang),
            "score": round(scores.get(cat, 0.0), 3),
            "added_by_risk": cat in added,
        }
        for cat in detected
    ]

    return {
        "dilemma": dilemma,
        "country": country,
        "sector": sector,
        "lang": lang,
        "using_fallback_classifier": getattr(classifier, "using_fallback", True),
        "llm_assisted_detection": llm_assisted,
        "detected_dimensions": dimensions_out,
        "all_scores": {cat: round(score, 3) for cat, score in scores.items()},
        "principles": principles,
        "regulations": regulations,
        "actions": actions,
        "disclaimer": DISCLAIMER.get(lang, DISCLAIMER[DEFAULT_LANG]),
        "has_results": bool(principles or regulations or actions),
    }
